[TECH-88] add staff pictures
concordiagamedev/CGDWebsite pull request #32
Opened 2024-10-10 03:33 UTC by maxxfreund

2024-10-16 02:29 UTC, maxxfreund commented
Asking for review on this cause it's done for now, but we should really look into loading times for our images cause the preview build is superrrr slow 😢 ⌛

2024-10-16 04:03 UTC, peach3es commented
each images profiles need to be max like 500-700kb, it's because they're like 2-5 mb at the moment

2024-10-24 21:24 UTC, peach3es reviewed
Looks good to me, finally have everyone's face on there. make sure to get rid of the section I reviewed

2024-10-24 21:24 UTC, peach3es commented on app/siteSettings/staff.json
>      },
Not going to be part of the club any further so we can get rid of this

2024-11-19 00:52 UTC, peach3es requested changes
check the changes that I requested plss

2024-11-19 00:52 UTC, peach3es commented on app/siteSettings/staff.json
>        "name": "Peter Tian",
can you change the picture to the one I put for the social media post? plsssss

2024-11-19 01:09 UTC, merged